module.exports={
  dev_sql_config:{
    host:"127.0.0.1",
    port:"3306",
    user:"root",
    password:"1q2w3e",
    database:"blog_sql"
  },
  product_sql_config:{
    host:"127.0.0.1",
    port:"3306",
    user:"root",
    password:"1q2w3e",
    database:"blog_sql"
  }
}